# Generated by Django 2.0.4 on 2018-05-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.CharField(default=None, max_length=128, unique=True),
        ),
    ]
